### ISSUE TITLE
Atleast 2 new samples found.

### ISSUE THREAD

**Issue by shownadda** [loneicewolf/Stuxnet-Source#3]
I was extracting resources from  a stuxnet sample and it's various droppers, when I found two that weren't uploaded to VT until I uploaded them.
I send you a friend request on discord so we can talk about it there, and hopefully do some research. 
Best regards. 
I have included those two files, and their VT page links. The password is "infected"
[StuxnetSamples.zip](https://github.com/loneicewolf/Stuxnet-Source/files/7538232/StuxnetSamples.zip)
https://www.virustotal.com/gui/file/88dd0628f7280ded93428d0e3a5337d20e1b3e2a9de57139c50cda3a1d6a3ed5
https://www.virustotal.com/gui/file/2861790fbe603ee0a6ba6b3e7a7840170d88dedd073303e11d1c6dc0a64c0fba

**Comment by loneicewolf** [comment]
hello, will take a look at them, I am quite busy with the OSCP (soon exam for me) but will check them eventually, 
have it good! //Accepted your discord req
